// <auto-generated />
using System;
using ClubHive.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClubHive.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClubClubExecutive", b =>
                {
                    b.Property<int>("ExecutivesId")
                        .HasColumnType("int");

                    b.Property<int>("ManagedClubsId")
                        .HasColumnType("int");

                    b.HasKey("ExecutivesId", "ManagedClubsId");

                    b.HasIndex("ManagedClubsId");

                    b.ToTable("ClubClubExecutive");
                });

            modelBuilder.Entity("ClubHive.Models.Club", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Clubs");
                });

            modelBuilder.Entity("ClubHive.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClubId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("EventTime")
                        .HasColumnType("time");

                    b.Property<string>("Room")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sponsors")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("ClubHive.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("Discriminator").HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ClubHive.Models.Admin", b =>
                {
                    b.HasBaseType("ClubHive.Models.User");

                    b.HasDiscriminator().HasValue("Admin");
                });

            modelBuilder.Entity("ClubHive.Models.ClubExecutive", b =>
                {
                    b.HasBaseType("ClubHive.Models.User");

                    b.HasDiscriminator().HasValue("ClubExecutive");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "a@email.com",
                            FirstName = "Nathan",
                            LastName = "Serrano",
                            Password = "123",
                            Rank = "Club Executive"
                        });
                });

            modelBuilder.Entity("ClubHive.Models.Student", b =>
                {
                    b.HasBaseType("ClubHive.Models.User");

                    b.HasDiscriminator().HasValue("Student");
                });

            modelBuilder.Entity("ClubClubExecutive", b =>
                {
                    b.HasOne("ClubHive.Models.ClubExecutive", null)
                        .WithMany()
                        .HasForeignKey("ExecutivesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClubHive.Models.Club", null)
                        .WithMany()
                        .HasForeignKey("ManagedClubsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClubHive.Models.Club", b =>
                {
                    b.HasOne("ClubHive.Models.User", null)
                        .WithMany("JoinedClubs")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("ClubHive.Models.Event", b =>
                {
                    b.HasOne("ClubHive.Models.Club", null)
                        .WithMany("Events")
                        .HasForeignKey("ClubId");
                });

            modelBuilder.Entity("ClubHive.Models.Club", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("ClubHive.Models.User", b =>
                {
                    b.Navigation("JoinedClubs");
                });
#pragma warning restore 612, 618
        }
    }
}
